Import('env')
cObj = []
c_src = Glob('*.c')

for src in c_src:
	cObj.append(env.Object(src, variant_dir=env['variant']))

cudaObj = []
cuda_src = Glob('*.cu')

for src in cuda_src:
	cudaObj.append(env.CUDAObject(src, variant_dir=env['variant']))

Return ('cObj', 'cudaObj')