Import('env')
c_src = Glob('*.c')
aObj = []
fdObj = []
#now add another object w/ the analytical jacobian defined
env_clone = env.Clone()
env_clone['CPPDEFINES'] += ['SUNDIALS_ANALYTIC_JACOBIAN']
for src in c_src:
	fdObj.append(env.Object(target='fd_' + str(src).replace('.c', '.o'),
							source=src, 
							variant_dir=env['variant']))
	aObj.append(env.Object(target='ana_' + str(src).replace('.c', '.o'),
							source=src, 
							variant_dir=env['variant']))

Return ('fdObj', 'aObj')