Import('env')
cObj = []
blacklist = ['fd_jacob', 'preconditioner']
c_src = Glob('*.c')
c_src = [x for x in c_src if not any(b in str(x) for b in blacklist)]

for src in c_src:
	cObj.append(env.Object(src, variant_dir=env['variant']))

cudaObj = []
cuda_src = Glob('*.cu')
cuda_src = [x for x in cuda_src if not any(b in str(x) for b in blacklist)]

if env['build_cuda']:
	for src in cuda_src:
		cudaObj.append(env.CUDAObject(src, variant_dir=env['variant']))

Return ('cObj', 'cudaObj')